syntax = "proto3";

package raffle;

service RaffleService {
  rpc SubscribeWinners(SubscribeRequest) returns (stream Winner);
  rpc PublishWinner(Winner) returns (PublishResponse);
  rpc HealthCheck(HealthCheckRequest) returns (stream HealthResponse);
}

message HealthCheckRequest {}

message HealthResponse {
  string status = 1;
}

message SubscribeRequest {
  string raffleId = 1;
}

message Winner {
  string raffleId = 1;
  string spinId = 2;
  string winnerId = 3;
  string winnerName = 4;
  string prize = 5;
  string eventType = 6;
  string message = 7;
}

message PublishResponse {
  bool accepted = 1;
}
